
--
DROP TABLE IF EXISTS CLIENTE_BIOMETRIA CASCADE;

DROP TABLE IF EXISTS BENEFICIARIO_TEL CASCADE;

DROP TABLE IF EXISTS CLIENTE_TEL CASCADE;

DROP TABLE IF EXISTS TRANSACCION CASCADE;

DROP TABLE IF EXISTS TARJETA CASCADE;

DROP TABLE IF EXISTS CUENTA CASCADE;

DROP TABLE IF EXISTS PRESTAMO CASCADE;

DROP TABLE IF EXISTS BENEFICIARIO CASCADE;

DROP TABLE IF EXISTS CLIENTE CASCADE;

CREATE TABLE CLIENTE (
    ID_Cliente SERIAL PRIMARY KEY,
    CURP VARCHAR(18) UNIQUE NOT NULL,
    Nacionalidad VARCHAR(50) NOT NULL,
    Estado_Civil VARCHAR(20) NOT NULL
);

CREATE TABLE PRESTAMO (
    ID_Prestamo SERIAL PRIMARY KEY,
    Estado VARCHAR(20) NOT NULL,
    Monto DECIMAL(15, 2) NOT NULL,
    ID_Cliente INT NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE (ID_Cliente) ON DELETE RESTRICT
);

CREATE TABLE BENEFICIARIO (
    ID_Beneficiario SERIAL PRIMARY KEY,
    Parentesco VARCHAR(30) NOT NULL,
    Porcentaje_Saldo DECIMAL(5, 2) NOT NULL,
    ID_Cliente INT NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE (ID_Cliente) ON DELETE CASCADE
);

CREATE TABLE CUENTA (
    No_Cuenta VARCHAR(20) PRIMARY KEY,
    Tipo_Cuenta VARCHAR(20) NOT NULL,
    Saldo DECIMAL(15, 2) NOT NULL DEFAULT 00.0,
    Tarjetas_Asociadas INT NOT NULL DEFAULT 0,
    ID_Cliente INT NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE (ID_Cliente) ON DELETE RESTRICT
);

CREATE TABLE TARJETA (
    No_Tarjeta VARCHAR(16) PRIMARY KEY,
    CVV VARCHAR(3) NOT NULL,
    Emisor VARCHAR(20) NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    No_Cuenta VARCHAR(20) NOT NULL,
    FOREIGN KEY (No_Cuenta) REFERENCES CUENTA (No_Cuenta) ON DELETE RESTRICT
);

CREATE TABLE TRANSACCION (
    ID_Transaccion SERIAL PRIMARY KEY,
    Cuenta_Destino VARCHAR(20) NOT NULL,
    Cuenta_Origen VARCHAR(20) NOT NULL,
    Monto DECIMAL(15, 2) NOT NULL,
    Tipo_Movimiento VARCHAR(30) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    No_Tarjeta VARCHAR(16),
    FOREIGN KEY (No_Tarjeta) REFERENCES TARJETA (No_Tarjeta) ON DELETE SET NULL,
    FOREIGN KEY (Cuenta_Origen) REFERENCES CUENTA (No_Cuenta) ON DELETE RESTRICT,
    FOREIGN KEY (Cuenta_Destino) REFERENCES CUENTA (No_Cuenta) ON DELETE RESTRICT
);

CREATE TABLE BENEFICIARIO_TEL (
    Tel VARCHAR(15) NOT NULL,
    ID_Beneficiario INT NOT NULL,
    PRIMARY KEY (TEL, ID_Beneficiario),
    FOREIGN KEY (ID_Beneficiario) REFERENCES BENEFICIARIO (ID_Beneficiario) ON DELETE CASCADE
);

CREATE TABLE CLIENTE_TEL (
    Tel VARCHAR(15) NOT NULL,
    ID_Cliente INT NOT NULL,
    PRIMARY KEY (Tel, ID_Cliente),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE (ID_Cliente) ON DELETE CASCADE
);

CREATE TABLE CLIENTE_BIOMETRIA (
    ID_Biometria SERIAL PRIMARY KEY,
    Tipo_Biometria VARCHAR(30) NOT NULL CHECK (
        Tipo_Biometria IN (
            'Huella Dactilar',
            'Rostro',
            'Iris'
        )
    ),
    Hash_referencia TEXT NOT NULL,
    ID_Cliente INT NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE (ID_Cliente) ON DELETE CASCADE
);

